server:
  port: 443
  ssl:
    key-store: "classpath:keystore.jks"
    key-store-password: changeit
    enabled: true
  http:
    port: 80

service:
  detailsTimeout: 1000000


  memcache:
    enabled: true
    configs:
      - ttl: 3600
        servers: memcached-dev1-0.memcached-dev1.dev.svc.cluster.local:11211
        name: search
      - ttl: 3600
        servers: memcached-dev1-0.memcached-dev1.dev.svc.cluster.local:11211
        name: autofill
      - ttl: 3600
        servers: memcached-dev1-0.memcached-dev1.dev.svc.cluster.local:11211
        name: rules
      - ttl: 3600
        servers: memcached-dev1-0.memcached-dev1.dev.svc.cluster.local:11211
        name: product
      - ttl: 60
        servers: memcached-dev1-0.memcached-dev1.dev.svc.cluster.local:11211
        name: pricing


  swagger:
    enabled: true

  solrService:
    enabled: true
    zkEnsembleDestination : zk-dev1-0.zk-hs-dev1.dev.svc.cluster.local:2181,zk-dev1-1.zk-hs-dev1.dev.svc.cluster.local:2181,zk-dev1-2.zk-hs-dev1.dev.svc.cluster.local:2181

  rulesService:
    enabled: false
    baseUrl: http://search-rules-service-dev1/siteId/api/rules
    version: 0

  availabilityService:
    enabled: false
    baseUrl: http://availability-service-dev1/siteId/api/productAvailability
    version: 0

  productService:
    enabled: true
    baseUrl: http://product-service-dev1/siteId/api/products
    version: 0

  pricingService:
    enabled: true
    baseUrl: http://pricing-service-dev1/siteId/api/pricing
    version: 0


logging:
  level:
    ROOT: WARN
    com: INFO
    com.ftd.services.search: DEBUG
#    org.apache.http: DEBUG
    org.springframework.web.client: DEBUG