service:
  memcache:
    enabled: false
  availabilityService:
    enabled: false
  pricingService:
    enabled: false
  productService:
    enabled: true
 
logging:
  level:
    ROOT: WARN
    com: INFO
    com.micro.services.search: DEBUG