service:

  detailsTimeout: 1000000

  memcache:
    enabled: false

  git:
    enabled: false
  swagger:
    enabled: false
  metrics:
    jmx:
      enabled: false
    dropwizard:
      enabled: false
    prometheus:
      enabled: false

   
logging:
  level:
    ROOT: WARN
    com: INFO
    com.ftd.services.search: DEBUG
#    org.apache.http: DEBUG
    org.springframework.web.client: DEBUG