#server:
#  context-path: /${spring.application.name}
#  tomcat:
#    accesslog:
#      enabled: false
#    basedir: .
spring:
  application:
    name: search
  cache:
    type: none
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
  cloud:
    config:
      allow-override: true
      override-none: false
      fail-fast: true
      override-system-properties: false
      enabled: false
  sleuth:
    web:
      enabled: true
    sampler:
      percentage: 100
  zipkin:
    base-url: http://localhost:8680/
    flush-interval: 15
    enabled: false
  redis:
    cluster:
      nodes: freshdapp01v1.ftdi.com:7000,freshdapp01v1.ftdi.com:7001,freshdapp01v1.ftdi.com:7002
      max-redirects: 3


service:
  metrics:
    dropwizard:
      enabled: true
    prometheus:
      enabled: true
    jmx:
      enabled: true
  git:
    enabled: true
  vip:
    enabled: false
  swagger:
    enabled: true
#    base-package: com.ftd.services.search.resource
  logging:
    enabled: true
  jsonp:
    enabled: true
  memcache:
    enabled: true
    configs:
      - ttl: 3600
        servers: localhost:11211
        name: search
      - ttl: 36000
        servers: localhost:11211
        name: autofill
      - ttl: 36000
        servers: localhost:11211
        name: rules
      - ttl: 36000
        servers: localhost:11211
        name: product
      - ttl: 60
        servers: localhost:11211
        name: pricing


  queryTimeAllowed : 10000
  groupLimitValue : 5
  breadCrumbList: categories
  sortList:
    - id
    - standard_price
  facetList:
    - categories
  rangeFacetList:
    - finalPrice
  autofillFacetList:
    - categories
  maxQueryRounds: 4
  spellCheckNumfoundThreshhold: 0
  mustMatchNumfoundThreshhold: 1
  searchEndpoint: /search
  browseEndpoint: /browse
  detailsEndpoint: /details
  autofillEndpoint: /autofill
  spellEndpoint: /spell
  productEndpoint: /product
  detailsTimeout: 1000
  document:
    autofill:
      desktop:
        size: 5
      mobile:
        size: 3
    search:
      desktop:
        size: 10
      mobile:
        size: 8
#    browse:
#      desktop:
#        size: 50
#      mobile:
#        size: 30
    spell:
      desktop:
        size: 3
      mobile:
        size: 3

  pagination:
    first:
      size: 3
    last:
      size: 3
    previous:
      size: 3
    next:
      size: 2

  solrService:
    enabled: true
    zkEnsembleDestination : freshdapp01v2.ftdi.com:2181
    collectionDestination : products
    zkTimeoutDestination : 20000
    queryTimeout : 10000
    version: 0

  rulesService:
    enabled: false
    baseUrl: http://localhost:8070/api/rules
    version: 0

  availabilityService:
    enabled: false
    baseUrl: http://35.227.193.133/api/productAvailability
    version: 0

  productService:
    enabled: true
    baseUrl: http://35.227.193.133/api/products
    version: 0

  pricingService:
    enabled: true
    baseUrl: http://35.227.252.218/api/pricing
    version: 0

  sitesBfMap:
    default: ftd_bso_order_cnt_l^3 ftd_bso_order_amt_d^4 ftd_bso_order_margin_d^2
    proflowers: proflowers_bso_order_cnt_l^3 proflowers_bso_order_amt_d^4 proflowers_bso_order_margin_d^2
    ftd: ftd_bso_order_cnt_l^3 ftd_bso_order_amt_d^4 ftd_bso_order_margin_d^2


hystrix:
   command.solrCommandKey.execution.isolation.thread.timeoutInMilliseconds: 2000
   command.solrCommandKey.circuitBreaker.requestVolumeThreshold: 4
   command.solrCommandKey.circuitBreaker.sleepWindowInMilliseconds: 60000
   command.solrCommandKey.metrics.rollingStats.timeInMilliseconds: 180000
   threadpool.solrThreadPoolKey.coreSize: 30
   threadpool.solrThreadPoolKey.metrics.rollingStats.timeInMilliseconds: 180000

   command.ruleServiceKey.execution.isolation.thread.timeoutInMilliseconds: 1000
   command.ruleServiceKey.circuitBreaker.requestVolumeThreshold: 4
   command.ruleServiceKey.circuitBreaker.sleepWindowInMilliseconds: 60000
   command.ruleServiceKey.metrics.rollingStats.timeInMilliseconds: 180000
   threadpool.ruleThreadPoolKey.coreSize: 30
   threadpool.ruleThreadPoolKey.metrics.rollingStats.timeInMilliseconds: 180000

   command.productServiceKey.execution.isolation.thread.timeoutInMilliseconds: 200000
   command.productServiceKey.circuitBreaker.requestVolumeThreshold: 4
   command.productServiceKey.circuitBreaker.sleepWindowInMilliseconds: 60000
   command.productServiceKey.metrics.rollingStats.timeInMilliseconds: 180000
   threadpool.productThreadPoolKey.coreSize: 30
   threadpool.productThreadPoolKey.metrics.rollingStats.timeInMilliseconds: 180000

   command.priceServiceKey.execution.isolation.thread.timeoutInMilliseconds: 200000
   command.priceServiceKey.circuitBreaker.requestVolumeThreshold: 4
   command.priceServiceKey.circuitBreaker.sleepWindowInMilliseconds: 60000
   command.priceServiceKey.metrics.rollingStats.timeInMilliseconds: 180000
   threadpool.priceThreadPoolKey.coreSize: 30
   threadpool.priceThreadPoolKey.metrics.rollingStats.timeInMilliseconds: 180000

   command.availabilityServiceKey.execution.isolation.thread.timeoutInMilliseconds: 2000
   command.availabilityServiceKey.circuitBreaker.requestVolumeThreshold: 4
   command.availabilityServiceKey.circuitBreaker.sleepWindowInMilliseconds: 60000
   command.availabilityServiceKey.metrics.rollingStats.timeInMilliseconds: 180000
   threadpool.availabilityThreadPoolKey.coreSize: 30
   threadpool.availabilityThreadPoolKey.metrics.rollingStats.timeInMilliseconds: 180000


#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#
#management:
#  security:
#    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.data.redis: DEBUG

#memcached:
#  cache:
#    servers: localhost:11211
#    mode: static
#    expiration: 5000


