service:
  memcache:
    enabled: false

  availabilityService:
    enabled: false

  productService:
    enabled: true
    timeout: 100000

  pricingService:
    enabled: false
 
logging:
  level:
    ROOT: WARN
    com: INFO
    com.micro.services.search: DEBUG