#server:
#  context-path: /${spring.application.name}
#  tomcat:
#    accesslog:
#      enabled: false
#    basedir: .
spring:
  application:
    name: search
  cache:
    type: none
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
  cloud:
    config:
      allow-override: true
      override-none: false
      fail-fast: true
      override-system-properties: false
      enabled: false
  sleuth:
    web:
      enabled: true
    sampler:
      percentage: 100
  zipkin:
    base-url: http://localhost:8680/
    flush-interval: 15
    enabled: false
#  redis:
#    cluster:
#      nodes: 10.222.92.54:7000,10.222.92.54:7001,10.222.92.54:7002
#    host: freshdapp01v1.ftdi.com
#    port: 7000
#    host: test-0001-001.udsdt6.0001.use1.cache.amazonaws.com
#    port: 6379
#    cluster:
#      nodes: freshdapp01v1.ftdi.com:7000
#    sentinel:
#      master: freshdapp01v1.ftdi.com
#      nodes: freshdapp01v1.ftdi.com:7000,freshdapp01v1.ftdi.com:7001,freshdapp01v1.ftdi.com:7002,freshdapp01v1.ftdi.com:7003
#    pool:
#      max-idle: 30
#      min-idle: 10


      #,freshdapp01v1.ftdi.com:7001:freshdapp01v1.ftdi.com:7002

service:
  metrics:
    dropwizard:
      enabled: true
    prometheus:
      enabled: true
    jmx:
      enabled: true
  git:
    enabled: true
  vip:
    enabled: false
  swagger:
    enabled: true
#    base-package: com.micro.services.search.resource
  logging:
    enabled: false
  memcache:
    enabled: true
    ttl: 3360
    servers: localhost:11211

  zkEnsembleDestination : freshdapp01v1.ftdi.com:2181
  collectionDestination : products
  zkTimeoutDestination : 20000
  solrQueryTimeout : 10000
  queryTimeAllowed : 10000
  groupLimitValue : 5
  breadCrumbList: index_name
  sortList: id
  maxQueryRounds: 4
  spellCheckNumfoundThreshhold: 0
  mustMatchNumfoundThreshhold: 1
  document:
    autofill:
      desktop:
        size: 5
      mobile:
        size: 3
    search:
      desktop:
        size: 10
      mobile:
        size: 8
    browse:
      desktop:
        size: 50
      mobile:
        size: 30
    spell:
      desktop:
        size: 3
      mobile:
        size: 3

  pagination:
    first:
      size: 3
    last:
      size: 2
    previous:
      size: 3
    next:
      size: 2

  rulesService:
    enabled: true
    baseUrl: http://localhost:8070/rules


hystrix:
   command.solrCommandKey.execution.isolation.thread.timeoutInMilliseconds: 2000
   command.solrCommandKey.circuitBreaker.requestVolumeThreshold: 4
   command.solrCommandKey.circuitBreaker.sleepWindowInMilliseconds: 60000
   command.solrCommandKey.metrics.rollingStats.timeInMilliseconds: 180000
   threadpool.solrThreadPoolKey.coreSize: 30
   threadpool.solrThreadPoolKey.metrics.rollingStats.timeInMilliseconds: 180000

   command.ruleServiceKey.execution.isolation.thread.timeoutInMilliseconds: 1000
   command.ruleServiceKey.circuitBreaker.requestVolumeThreshold: 4
   command.ruleServiceKey.circuitBreaker.sleepWindowInMilliseconds: 60000
   command.ruleServiceKey.metrics.rollingStats.timeInMilliseconds: 180000
   threadpool.ruleThreadPoolKey.coreSize: 30
   threadpool.ruleThreadPoolKey.metrics.rollingStats.timeInMilliseconds: 180000



endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

#logging:
#  level:
#    ROOT: INFO
#    com.amazonaws: DEBUG

