server:
  context-path: /${spring.application.name}
  tomcat:
    accesslog:
      enabled: false
    basedir: .

spring:
  application:
    name: generic-search
#  cache:
#    type: none
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
  cloud:
    config:
      allow-override: true
      override-none: false
      fail-fast: true
      override-system-properties: false
      enabled: false
  sleuth:
    web:
      enabled: true
    sampler:
      percentage: 100
  zipkin:
    base-url: http://localhost:8680/
    flush-interval: 15
    enabled: false

service:
  metrics:
    dropwizard:
      enabled: true
    prometheus:
      enabled: true
  git:
    enabled: true
  vip:
    enabled: true
  swagger:
    enabled: true
  logging:
    enabled: true




  zkEnsembleDestination : freshdapp01v1.ftdi.com:2181
  collectionDestination : products
  zkTimeoutDestination : 20000
  solrQueryTimeout : 10000
  queryTimeAllowed : 10000
  groupLimitValue : 5
  defaultRows: 10
  defaultMobileRows: 5
  breadCrumbList: index_name
  sortList: id
  maxQueryRounds: 5
  spellCheckNumfoundThreshhold: 0
  mustMatchNumfoundThreshhold: 1
  pagination:
    first:
      size: 3
    last:
      size: 2
    previous:
      size: 3
    next:
      size: 2

  rulesService:
    baseUrl: http://localhost:8080/demo/rules


memcached:
  cache:
    servers: localhost:11211
    mode: static

hystrix:
   command.solrCommandKey.execution.isolation.thread.timeoutInMilliseconds: 2000
   command.solrCommandKey.circuitBreaker.requestVolumeThreshold: 4
   command.solrCommandKey.circuitBreaker.sleepWindowInMilliseconds: 60000
   command.solrCommandKey.metrics.rollingStats.timeInMilliseconds: 180000
   threadpool.solrThreadPoolKey.coreSize: 30
   threadpool.solrThreadPoolKey.metrics.rollingStats.timeInMilliseconds: 180000





endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

logging:
  level:
    ROOT: INFO
    com.amazonaws: DEBUG

