---
apiVersion: v1
kind: Service
metadata:
  name: search-service-group
  labels:
    app: search
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: server
  selector:
    app: search
    ns: group
  #type: LoadBalancer
  type: NodePort