---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: search-deployment
  labels:
    app: search
spec:
  selector:
    matchLabels:
      app: search
  replicas: 3
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        imagePullPolicy: Always
        image: "sekhrivijay/generic-search:10936516e4a5452580543a3b1427adc694526a86"
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
          name: server
        env:
        - name: SERVICE_ZKENSEMBLEDESTINATION
          value: "zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"        command:
#        command:
#        - java
#        - "-Dservice.zkEnsembleDestination=zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
#        - -jar
#        - generic-search-1.0-SNAPSHOT.jar
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            #httpHeaders:
            # - name: X-Custom-Header
            #  value: Awesome
          initialDelaySeconds: 65
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "/query?q=*:*"
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
