---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-hpa-group
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: search-deployment-group
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 0.5G
#  - type: Pods
#    pods:
#      metricName: current_connections
#      targetAverageValue: 10