---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: search-service-group
  labels:
    app: search
    ns: group
spec:
  selector:
    matchLabels:
      app: search
      ns: group
  replicas: 1
  template:
    metadata:
      labels:
        app: search
        ns: group
    spec:
      containers:
      - name: search-service
        imagePullPolicy: Always
        image: "gcr.io/deep-thought-185318/search-service:e6b8b6fdce964f0b2c0aaecf9256d16fdfc6bfc8"
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
          name: server
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "group"
        - name: SERVICE_SOLRSERVICE_ZKENSEMBLEDESTINATION
          value: "zk-group-0.zk-hs-group.default.svc.cluster.local:2181,zk-group-1.zk-hs-group.default.svc.cluster.local:2181,zk-group-2.zk-hs-group.default.svc.cluster.local:2181"
        - name: SERVICE_MEMCACHE_ENABLED
          value: "false"
        - name: SERVICE_RULESSERVICE_BASEURL
          value: "http://search-rules-service-group/siteId/api/rules"
        - name: SERVICE_PRODUCTSERVICE_BASEURL
          value: "http://product-service-group/siteId/api/products"
        - name: SERVICE_PRICINGSERVICE_BASEURL
          value: "http://pricing-service-group/siteId/api/pricing"
        - name: JAVA_ARGS
          value: "-Dservice.memcache.configs[0].servers=memcached-group-0.memcached-group.default.svc.cluster.local:11211 -Dservice.memcache.configs[1].servers=memcached-group-0.memcached-group.default.svc.cluster.local:11211"

#        command:
#        - java
#        - "-Dservice.zkEnsembleDestination=zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
#        - -jar
#        - generic-search-1.0-SNAPSHOT.jar
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            #httpHeaders:
            # - name: X-Custom-Header
            #  value: Awesome
          initialDelaySeconds: 65
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10