---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search
spec:
  ports:
  - port: 8080
    #targetPort: 8080
    name: server
  selector:
    app: search
  type: LoadBalancer
  #type: NodePort


