---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search
spec:
  ports:
  - port: 8080
    #targetPort: 8080
    name: server
  selector:
    app: search
  type: LoadBalancer
  #type: NodePort
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: search-pdb
spec:
  selector:
    matchLabels:
      app: search
  maxUnavailable: 3
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: search-deployment
  labels:
    app: search
spec:
  selector:
    matchLabels:
      app: search
  #serviceName: search-service
  replicas: 3
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        imagePullPolicy: Always
        image: "sekhrivijay/generic-search:24a8b7e5d802b545fbe1457cbac288dbd03de25e"
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
          name: server
        command:
        - java
        - "-Dservice.zkEnsembleDestination=zk-0.zk-hs.default.svc.cluster.local:2181,zk-1.zk-hs.default.svc.cluster.local:2181,zk-2.zk-hs.default.svc.cluster.local:2181"
        - -jar
        - generic-search-1.0-SNAPSHOT.jar
        livenessProbe:
          httpGet:
            path: /generic-search/health
            port: 8080
            #httpHeaders:
            # - name: X-Custom-Header
            #  value: Awesome
          initialDelaySeconds: 35
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: "/generic-search/query?q=*:*"
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 3


---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: search-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: search-deployment
  minReplicas: 8
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 20
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 0.5G
#  - type: Pods
#    pods:
#      metricName: current_connections
#      targetAverageValue: 10