# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['-U', '-DskipTests', '-B', 'clean', 'install']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/search-service', '.']

images: ['gcr.io/$PROJECT_ID/search-service']

